name: global_student
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_fadein: ^2.0.0
  pinput: ^2.2.20
  intl_phone_field: ^3.1.0
  dropdown_button2: ^2.0.0
  flutter_image_slideshow: ^0.1.4
  lottie: ^2.1.0
  file_picker: ^5.0.1
  path_provider:
  filter_list: ^1.0.2
  shared_preferences: ^2.0.18
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.6
  image_picker: ^0.8.7+5
  flip_card: ^0.5.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  get: ^4.6.5
  expansion_tile_card: ^3.0.0
  animated_text_kit: ^4.2.2
  path: ^1.8.3
  rename: ^2.1.1
  image_cropper: ^4.0.1
  permission_handler: ^11.0.1
  bottom_picker: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-Bold.ttf
        - asset: fonts/Outfit-Regular.ttf
        - asset: fonts/Outfit-SemiBold.ttf
